name:                geometry
version:             0.1.0.0
github:              "githubuser/geometry"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/geometry#readme>

dependencies:
- base >= 4.7 && < 5
- gloss >= 1.13.2.1 && < 1.15.0.0
- containers >= 0.6 && < 0.7

library:
  source-dirs: src

executables:
  segment-intersections:
    main:                Main.hs
    source-dirs:         app/segment_intersections
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geometry
    
  convexhull:
    main:                Main.hs 
    source-dirs:         app/convexhull
    ghc-options:
    - -threaded 
    - -rtsopts
    - -with-rtsopts=-N 
    dependencies:
    - geometry

tests:
  geometry-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geometry
    - hspec >= 2.8 && < 2.11
    - QuickCheck >= 2.13 && < 2.15